### ISSUE TITLE
JSON columns

### ISSUE THREAD

**Issue by Intrflex** [korridor/laravel-has-many-merged#1]
any chance of this working where the field is json data? for example {"email":"help@intrflex.com"}?

**Comment by korridor** [comment]
First of all, thank you for opening an issue.
So I would like to help you, but I need some more information.
Is this about a JSON API endpoint?
If yes: Is the json encoded as a string or is it simply an object inside a json request?

**Comment by korridor** [comment]
First of all, thank you for opening an issue.
So I would like to help you but I need some more information.
Do I understand correctly that you want to use the email field in the JSON as a foreign key?
Can you send me what your two "hasMany" relations look like which you want to merge into one?

**Comment by Intrflex** [comment]
no problem,  
I currently use another package staudenmeir/eloquent-JSON-relations,  as the data I need to access is inside a JSON array for example 
`[{"name": "", "email": "1@1.com"}]` now the issue I have is that package doesn't allow for multiple foreign keys as I need to be able to select from 2 columns that's when I came across yours but default laravel doesn't allow for relationships on an array of object

for example, I have a contacts table with email an column i want to be able to select from my inbound_emails table the to and from the column where it contains my JSON, but as stated the to column contains an array of JSON objects i hope this makes sense-

**Comment by korridor** [comment]
Ok I think I understand your issue.
Can you still send me the code of the two hasMany relations to be sure?

**Comment by Intrflex** [comment]
```
public function mailTo()
    {

      return $this->hasManyJson(InboundEmail::class, 'to[]->email' , 'email')->where('public', 1);
    }

    public function mailFrom(): HasManyJson
    {
        return $this->hasManyJson(InboundEmail::class, 'from->email', 'email')->where('public', 1);
    }

```

thats the relationships

**Comment by korridor** [comment]
Sorry for the late reply. I looked into it and I think it's a bit beyond the scope of the project. I also didn't find a way to use elegant features of the package "staudenmeir/eloquent-JSON-relations" for this.
If you have a nice solution for this I would be happy about a pull request though.
