### ISSUE TITLE
withCount doesn't work

### ISSUE THREAD

**Issue by MahdiGraph** [korridor/laravel-has-many-merged#3]
Everything's Great 👌
"with" method is working but only problem i know is that "withCount" method doesn't working

**Comment by korridor** [comment]
Thanks for the ticket!
I just tested this and you are right this does not work at the moment.
I'll try to fix this as soon as possible!

**Comment by korridor** [comment]
Pull request: #4

**Comment by korridor** [comment]
This should be fixed with release 0.0.3
@MahdiGraph Please check if this fixes your issue.
