### ISSUE TITLE
I'm a bit confused!

### ISSUE THREAD

**Issue by EriksonEnterprises** [korridor/laravel-has-many-merged#9]
Hello, trying to use this for shops...

This is my model:

```
class Shop extends Model
{
    use HasFactory, SoftDeletes, HasManyMergedRelation;

    public function locations(): HasManyMerged
    {
        return $this->hasManyMerged(ShopAddress::class, ShopNumber::class);
    }

    public function addresses(): HasMany
    {
        return $this->hasMany(ShopAddress::class, 'shop_id');
    }

    public function numbers(): HasMany
    {
        return $this->hasMany(ShopNumber::class, 'shop_id');
    }
}
```

How would I make locations relationship work??

**Comment by korridor** [comment]
Hi @jamesautodude,

the package can only merge two HasMany relations if they both point to the same model.

The goal behind the merged relation is that it is possible to load both of them with one database query and maybe query them.
With two different models it is not possible to do this in one query and the result collection would also contain a mixture of two different types, which is probably not the best idea.

If you have any more questions, feel free to ask.
